services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_R2_ACCESS_KEY_ID=${CLOUDFLARE_R2_ACCESS_KEY_ID}
      - CLOUDFLARE_R2_BUCKET_NAME=${CLOUDFLARE_R2_BUCKET_NAME}
      - CLOUDFLARE_R2_SECRET_ACCESS_KEY=${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
      - GITHUB_OAUTH_APP_CLIENT_ID=${GITHUB_OAUTH_APP_CLIENT_ID}
      - GITHUB_OAUTH_APP_CLIENT_SECRET=${GITHUB_OAUTH_APP_CLIENT_SECRET}
      - GITHUB_OWNER=jackdbd
      - GITHUB_REPO=giacomodebidda-content
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JWKS=${JWKS}
      - NODE_ENV=development
      - PORT=3001
      - SECURE_SESSION_KEY_ONE=${SECURE_SESSION_KEY_ONE}
      - SECURE_SESSION_KEY_TWO=${SECURE_SESSION_KEY_TWO}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./micropub-dev.db:/home/micropub-user/micropub/micropub-dev.db
