export const ACCEPT = 'application/vnd.github+json'
export const BASE_URL = 'https://api.github.com'
export const GITHUB_API_VERSION = '2022-11-28'
export const DELETED_PREFIX = 'deleted/'
export const REF = 'main'
