name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  audit-build-test-deploy:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4
      
      - name: 🖥️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          # https://github.com/nodejs/Release/blob/main/CODENAMES.md
          node-version: lts/Iron

      - run: npm ci --include dev --include prod

      - name: 🛡️ Audit security
        continue-on-error: true
        run: npm audit --audit-level=moderate
      
      - name: 🔧 Build app
        run: npm run build

      - name: 🔍 Test app
        run: npm run test

      - name: Deploy to Fly
        id: fly_deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only
          # Unfortunately, capturing stdout with the following command does not work:
          # echo "stdout=$(flyctl deploy --remote-only)" >> $GITHUB_OUTPUT

      - run: echo "fly deploy is ${{ toJSON(steps.fly_deploy) }}"
      # - run: echo "fly deploy.outputs.stdout is ${{ steps.fly_deploy.outputs.stdout }}"

      - name: 💬 Send notification to Telegram
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: false
          message: |
            <b>Deploy to Fly</b>

            Repository: <a href="${{ github.event.repository.html_url }}">${{ github.event.repository.full_name }}</a>

